export {Home} from './home/Home';
export {NotFound} from './notFound/NotFound';
export {About} from "./about/About";
export {Team} from "./team/Team";
export {Term} from "./term/Term";
export {Privacy} from "./privacy/Privacy";
export {Contact} from "./contact/Contact";
export {Header} from './header/Header';
export {Footer} from './footer/Footer';