# Generated by Django 3.2 on 2022-05-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('latitude', models.DecimalField(db_index=True, decimal_places=5, max_digits=8)),
                ('longitude', models.DecimalField(db_index=True, decimal_places=5, max_digits=8)),
                ('google_place_id', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=8, unique=True)),
            ],
            options={
                'db_table': 'location',
            },
        ),
    ]
